resolver: lts-13.17

image:
  containers:
    - name: "circleci-failure-tracker-img-small"
      base: fpco/stack-run
      add:
        static: /data/static
      entrypoints:
        - my-webapp

packages:
- webfront
- fetcher

extra-deps:
- time-1.9.2

allow-newer: true
