resolver: lts-13.17

image:
  containers:
    - name: "circleci-failure-tracker-img-small"
      base: fpco/stack-run
      add:
        static: /data/static
      entrypoints:
        - my-webapp

packages:
- webservice
- fetcher
- oneoff
- session-demo

extra-deps:
- time-1.9.2
- wai-session-clientsession-0.1
- github-0.21
- json-stream-0.4.2.4

allow-newer: true
