name: webfront
version: '0.1.0.0'
author: Karl Ostmo
maintainer: kostmo@gmail.com
license: BSD3
dependencies:
- base
- aeson

executables:
  my-webapp:
    main: Main.hs
    source-dirs: src
    ghc-options:
    - -W
    - -Wall
    - -fwarn-tabs
    - -fhpc
    - -threaded
    dependencies:
    - fetcher
    - split
    - bytestring
    - scotty
    - blaze-html
    - blaze-markup
    - directory
    - filepath
    - text
    - optparse-applicative
    - wai
    - wai-extra
    - wai-middleware-static
    - securemem
