name: webfront
version: '0.1.0.0'
author: Karl Ostmo
maintainer: kostmo@gmail.com
license: BSD3
dependencies:
- base
- aeson

executables:
  my-webapp:
    main: Main.hs
    source-dirs: src
    ghc-options:
    - -W
    - -Wall
    - -fwarn-tabs
    - -fhpc
    - -threaded
    dependencies:
    - fetcher
    - split
    - bytestring
    - scotty
    - filepath
    - text
    - optparse-applicative
    - wai
    - wai-extra
    - wai-middleware-static
    - hoauth2
    - uri-bytestring
    - hashable
    - unordered-containers
    - http-conduit
    - mustache
    - mtl
    - data-default
    - containers
    - MissingH
    - vault
    - lens
    - vector 
    - lens-aeson
    - http-client-tls
    - http-client
    - time
    - wai-session
    - wai-session-clientsession
    - clientsession
    - github
    - transformers
    - network-uri 
    - safe
