name: fetcher
version: '0.1.0.0'
author: Karl Ostmo
maintainer: kostmo@gmail.com
license: BSD3
dependencies:
- base
- text
- directory
- async

library:
  source-dirs: src
  ghc-options:
  - -W
#  - -Werror
  - -fwarn-tabs
  - -O2
  - -threaded
  - -with-rtsopts=-N4
  dependencies:
    - wreq
    - lens
    - lens-aeson
    - bytestring
    - aeson
    - vector
    - time
    - regex-pcre
    - postgresql-simple
    - pureMD5
    - filepath


executables:
  run-scanner:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -W
    - -fwarn-tabs
    - -O2
    - -threaded
    - -with-rtsopts=-N4
    dependencies:
    - fetcher
    - optparse-applicative
    - parallel-io
