name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1.1
      with:
        enable-stack: true
        stack-no-global: true
        stack-version: latest

    # Restore timestamps to help stack not rebuild unchanged files.
    # https://stackoverflow.com/questions/60906336
    # https://stackoverflow.com/a/36243002/84401
    # https://www.reddit.com/r/haskell/comments/g00ldn/haskell_stack_on_github_actions/
    - name: Restore source file timestamps
      run: |
        git ls-tree -r --name-only HEAD | while read filename; do
          TS="$(git log -1 --format="%ct" -- ${filename})"
          touch "${filename}" -mt "$(date --date="@$TS" "+%Y%m%d%H%M.%S")"
        done
    # things to be cached/restored:
    - name: Cache stack global package db
      id:   stack-global
      uses: actions/cache@v2
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack-global-${{ hashFiles('**.yaml') }}
        restore-keys: |
          ${{ runner.os }}-stack-global
    - name: Cache stack-installed programs in ~/.local/bin
      id:   stack-programs
      uses: actions/cache@v2
      with:
        path: ~/.local/bin
        key: ${{ runner.os }}-stack-programs-${{ hashFiles('**.yaml') }}
        restore-keys: |
          ${{ runner.os }}-stack-programs
    - name: Cache .stack-work
      uses: actions/cache@v2
      with:
        path: .stack-work
        key: ${{ runner.os }}-stack-work-${{ hashFiles('**.yaml') }}
        restore-keys: |
          ${{ runner.os }}-stack-work


    - name: Build
      working-directory: app
      run: |
       stack setup --no-terminal
       stack build -j2 --fast --no-terminal
    - name: Test
      working-directory: app
      run: stack test --fast --no-terminal
