name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      # - STACK_YAML=app/stack.yaml
      matrix:
        os: [ubuntu-latest, macOS-latest]
        # use this to include any dependencies from OS package managers
        include: []
        # - os: macOS-latest
        #   brew: anybrewdeps
        # - os: ubuntu-latest
        #   apt-get: happy libblas-dev liblapack-dev

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - if:  matrix.os  == 'macos-latest'
      run: brew install haskell-stack
    - name: Build
      run: |
       set-env STACK_YAML=app/stack.yaml
       stack setup --no-terminal
       stack build -j2 --fast --no-terminal
    - name: Test
      run: stack test --fast --no-terminal
